node {
    stage ("checkout") {
        git 'https://github.com/pei-wang/emailService.git'
    }

    stage ("build"){
        sh 'pwd'
        sh 'chmod a+x gradlew'
        sh './gradlew build'
    }

    stage ("deploy"){
        sh 'java -jar emailService-0.0.1-SNAPSHOT.jar &'
    }
}